apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Port, über den der Service erreichbar ist
      targetPort: 80    # Port im Container
  type: ClusterIP       # Innerhalb des Clusters erreichbar