pipeline {
    agent any

    stages {
        stage('Build - Backend') {
                    steps {
                        sh 'mvn clean install -P dev'
                    }
                }

                stage('Build - Frontend') {
                    steps {
                        sh 'npm install && npm run build'
                    }
                }
    }
}